=== DenisBohnat/SaxStaxDomParsers/resources/FamilySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.myschema.by/FamilySchema" xmlns:xl="http://www.myschema.by/FamilySchema"
	elementFormDefault="qualified">

	<!--<xs:element name="families" type="xl:families_type"> -->
	<xs:element name="families">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="family" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mother">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string" />
										<xs:element name="maiden-name" type="xs:string" />
										<xs:element name="surname" type="xs:string" />
										<xs:element name="age" type="xs:int" />
										<xs:element name="children">
											<xs:complexType>
												<xs:attribute name="count" type="xs:int" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="father">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string" />
										<xs:element name="surname" type="xs:string" />
										<xs:element name="age" type="xs:int" />
										<xs:element name="children" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="count" type="xs:int" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DenisBohnat/SaxStaxDomParsers/resources/Family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<families xmlns="http://www.myschema.by/FamilySchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.myschema.by/FamilySchema FamilySchema.xsd">
	<family name="Ivanovy">
		<mother>
			<name>Sveta</name>
			<maiden-name>Miranovich</maiden-name>
			<surname>Barkun</surname>
			<age>32</age>
			<children count="3" />
		</mother>
		<father>
			<name>Ivan</name>
			<surname>Barkun</surname>
			<age>36</age>
		</father>
	</family>
	<family name="Petrovy">
		<mother>
			<name>Anna</name>
			<maiden-name>Glukova</maiden-name>
			<surname>Petrova</surname>
			<age>28</age>
			<children count="3" />
		</mother>
		<father>
			<name>Ihar</name>
			<surname>Petrov</surname>
			<age>36</age>
		</father>
	</family>
</families>
